---
driver:
  # name: vagrant
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
  # name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  # - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[splunk::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: splunk_forwarder
    run_list:
      - recipe[splunk_forwarder_test::default]
    verifier:
      inspec_tests:
        - test/splunk_forwarder/default
    attributes:
