source 'https://rubygems.org'

gem 'berkshelf'
gem 'chefspec'
gem 'cookstyle'
gem 'foodcritic'
gem 'kitchen-dokken'
gem 'kitchen-inspec'
# gem 'kitchen-vagrant'
gem 'rake'
gem 'stove'
gem 'test-kitchen'
gem 'tomlrb'
gem 'thor', '0.19.1'